"""Structured extraction: document-type schemas, deterministic finders, span grounding."""

from .extractors import FieldFinder, FieldMatch
from .grounding import (
    GroundingError,
    Location,
    build_provenance,
    ground,
    is_grounded,
    locate,
    locate_in_page,
)
from .normalize import (
    GroupingStyle,
    MoneyCrossCheck,
    ParsedArea,
    ParsedDate,
    ParsedMoney,
    cross_check_money,
    detect_grouping,
    normalise_name,
    parse_area,
    parse_date,
    parse_indian_words,
    parse_money_figures,
)
from .schema import (
    SCHEMAS,
    DocumentSchema,
    FieldSpec,
    PageScope,
    Select,
    schema_for,
    supported_types,
)
from .service import ExtractedField, ExtractionResult, ExtractionService

__all__ = [
    "SCHEMAS",
    "DocumentSchema",
    "ExtractedField",
    "ExtractionResult",
    "ExtractionService",
    "FieldFinder",
    "FieldMatch",
    "FieldSpec",
    "GroundingError",
    "GroupingStyle",
    "Location",
    "MoneyCrossCheck",
    "PageScope",
    "ParsedArea",
    "ParsedDate",
    "ParsedMoney",
    "Select",
    "build_provenance",
    "cross_check_money",
    "detect_grouping",
    "ground",
    "is_grounded",
    "locate",
    "locate_in_page",
    "normalise_name",
    "parse_area",
    "parse_date",
    "parse_indian_words",
    "parse_money_figures",
    "schema_for",
    "supported_types",
]
